// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ShortenURLResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ShortenURLJSONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLJSONRequest) Reset() {
	*x = ShortenURLJSONRequest{}
	mi := &file_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLJSONRequest) ProtoMessage() {}

func (x *ShortenURLJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLJSONRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLJSONRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenURLJSONRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenURLJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLJSONResponse) Reset() {
	*x = ShortenURLJSONResponse{}
	mi := &file_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLJSONResponse) ProtoMessage() {}

func (x *ShortenURLJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLJSONResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLJSONResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ShortenURLJSONResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ShortenURLJSONResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ShortenURLBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchRequest        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLBatchRequest) Reset() {
	*x = ShortenURLBatchRequest{}
	mi := &file_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLBatchRequest) ProtoMessage() {}

func (x *ShortenURLBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLBatchRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *ShortenURLBatchRequest) GetItems() []*BatchRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *BatchRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenURLBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchResponse       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLBatchResponse) Reset() {
	*x = ShortenURLBatchResponse{}
	mi := &file_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLBatchResponse) ProtoMessage() {}

func (x *ShortenURLBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLBatchResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *ShortenURLBatchResponse) GetItems() []*BatchResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShortenURLBatchResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *BatchResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RedirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectRequest) Reset() {
	*x = RedirectRequest{}
	mi := &file_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectRequest) ProtoMessage() {}

func (x *RedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectRequest.ProtoReflect.Descriptor instead.
func (*RedirectRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *RedirectRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type RedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectResponse) Reset() {
	*x = RedirectResponse{}
	mi := &file_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectResponse) ProtoMessage() {}

func (x *RedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectResponse.ProtoReflect.Descriptor instead.
func (*RedirectResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *RedirectResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RedirectResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserURL             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLsResponse) Reset() {
	*x = UserURLsResponse{}
	mi := &file_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsResponse) ProtoMessage() {}

func (x *UserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLsResponse.ProtoReflect.Descriptor instead.
func (*UserURLsResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *UserURLsResponse) GetItems() []*UserURL {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UserURLsResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UserURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURL) Reset() {
	*x = UserURL{}
	mi := &file_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURL) ProtoMessage() {}

func (x *UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURL.ProtoReflect.Descriptor instead.
func (*UserURL) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *UserURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCodes    []string               `protobuf:"bytes,1,rep,name=short_codes,json=shortCodes,proto3" json:"short_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserURLsRequest) GetShortCodes() []string {
	if x != nil {
		return x.ShortCodes
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{13}
}

func (x *PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PingResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *StatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *StatsResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_shortener_proto protoreflect.FileDescriptor

const file_shortener_proto_rawDesc = "" +
	"\n" +
	"\x0fshortener.proto\x12\tshortener\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\x11ShortenURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"D\n" +
	"\x12ShortenURLResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\")\n" +
	"\x15ShortenURLJSONRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"H\n" +
	"\x16ShortenURLJSONResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"G\n" +
	"\x16ShortenURLBatchRequest\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.shortener.BatchRequestR\x05items\"X\n" +
	"\fBatchRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"a\n" +
	"\x17ShortenURLBatchResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.shortener.BatchResponseR\x05items\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"S\n" +
	"\rBatchResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"0\n" +
	"\x0fRedirectRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"F\n" +
	"\x10RedirectResponse\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"T\n" +
	"\x10UserURLsResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.shortener.UserURLR\x05items\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"I\n" +
	"\aUserURL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"8\n" +
	"\x15DeleteUserURLsRequest\x12\x1f\n" +
	"\vshort_codes\x18\x01 \x03(\tR\n" +
	"shortCodes\"@\n" +
	"\fPingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"Q\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status2\xed\x04\n" +
	"\tShortener\x12K\n" +
	"\n" +
	"ShortenURL\x12\x1c.shortener.ShortenURLRequest\x1a\x1d.shortener.ShortenURLResponse\"\x00\x12W\n" +
	"\x0eShortenURLJSON\x12 .shortener.ShortenURLJSONRequest\x1a!.shortener.ShortenURLJSONResponse\"\x00\x12Z\n" +
	"\x0fShortenURLBatch\x12!.shortener.ShortenURLBatchRequest\x1a\".shortener.ShortenURLBatchResponse\"\x00\x12O\n" +
	"\x12RedirectByShortURL\x12\x1a.shortener.RedirectRequest\x1a\x1b.shortener.RedirectResponse\"\x00\x12D\n" +
	"\vGetUserURLs\x12\x16.google.protobuf.Empty\x1a\x1b.shortener.UserURLsResponse\"\x00\x12L\n" +
	"\x0eDeleteUserURLs\x12 .shortener.DeleteUserURLsRequest\x1a\x16.google.protobuf.Empty\"\x00\x129\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x17.shortener.PingResponse\"\x00\x12>\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x18.shortener.StatsResponse\"\x00B\x16Z\x14./internal/app/protob\x06proto3"

var (
	file_shortener_proto_rawDescOnce sync.Once
	file_shortener_proto_rawDescData []byte
)

func file_shortener_proto_rawDescGZIP() []byte {
	file_shortener_proto_rawDescOnce.Do(func() {
		file_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortener_proto_rawDesc), len(file_shortener_proto_rawDesc)))
	})
	return file_shortener_proto_rawDescData
}

var file_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_shortener_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),       // 0: shortener.ShortenURLRequest
	(*ShortenURLResponse)(nil),      // 1: shortener.ShortenURLResponse
	(*ShortenURLJSONRequest)(nil),   // 2: shortener.ShortenURLJSONRequest
	(*ShortenURLJSONResponse)(nil),  // 3: shortener.ShortenURLJSONResponse
	(*ShortenURLBatchRequest)(nil),  // 4: shortener.ShortenURLBatchRequest
	(*BatchRequest)(nil),            // 5: shortener.BatchRequest
	(*ShortenURLBatchResponse)(nil), // 6: shortener.ShortenURLBatchResponse
	(*BatchResponse)(nil),           // 7: shortener.BatchResponse
	(*RedirectRequest)(nil),         // 8: shortener.RedirectRequest
	(*RedirectResponse)(nil),        // 9: shortener.RedirectResponse
	(*UserURLsResponse)(nil),        // 10: shortener.UserURLsResponse
	(*UserURL)(nil),                 // 11: shortener.UserURL
	(*DeleteUserURLsRequest)(nil),   // 12: shortener.DeleteUserURLsRequest
	(*PingResponse)(nil),            // 13: shortener.PingResponse
	(*StatsResponse)(nil),           // 14: shortener.StatsResponse
	(*emptypb.Empty)(nil),           // 15: google.protobuf.Empty
}
var file_shortener_proto_depIdxs = []int32{
	5,  // 0: shortener.ShortenURLBatchRequest.items:type_name -> shortener.BatchRequest
	7,  // 1: shortener.ShortenURLBatchResponse.items:type_name -> shortener.BatchResponse
	11, // 2: shortener.UserURLsResponse.items:type_name -> shortener.UserURL
	0,  // 3: shortener.Shortener.ShortenURL:input_type -> shortener.ShortenURLRequest
	2,  // 4: shortener.Shortener.ShortenURLJSON:input_type -> shortener.ShortenURLJSONRequest
	4,  // 5: shortener.Shortener.ShortenURLBatch:input_type -> shortener.ShortenURLBatchRequest
	8,  // 6: shortener.Shortener.RedirectByShortURL:input_type -> shortener.RedirectRequest
	15, // 7: shortener.Shortener.GetUserURLs:input_type -> google.protobuf.Empty
	12, // 8: shortener.Shortener.DeleteUserURLs:input_type -> shortener.DeleteUserURLsRequest
	15, // 9: shortener.Shortener.Ping:input_type -> google.protobuf.Empty
	15, // 10: shortener.Shortener.GetStats:input_type -> google.protobuf.Empty
	1,  // 11: shortener.Shortener.ShortenURL:output_type -> shortener.ShortenURLResponse
	3,  // 12: shortener.Shortener.ShortenURLJSON:output_type -> shortener.ShortenURLJSONResponse
	6,  // 13: shortener.Shortener.ShortenURLBatch:output_type -> shortener.ShortenURLBatchResponse
	9,  // 14: shortener.Shortener.RedirectByShortURL:output_type -> shortener.RedirectResponse
	10, // 15: shortener.Shortener.GetUserURLs:output_type -> shortener.UserURLsResponse
	15, // 16: shortener.Shortener.DeleteUserURLs:output_type -> google.protobuf.Empty
	13, // 17: shortener.Shortener.Ping:output_type -> shortener.PingResponse
	14, // 18: shortener.Shortener.GetStats:output_type -> shortener.StatsResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_shortener_proto_init() }
func file_shortener_proto_init() {
	if File_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortener_proto_rawDesc), len(file_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortener_proto_goTypes,
		DependencyIndexes: file_shortener_proto_depIdxs,
		MessageInfos:      file_shortener_proto_msgTypes,
	}.Build()
	File_shortener_proto = out.File
	file_shortener_proto_goTypes = nil
	file_shortener_proto_depIdxs = nil
}
